CREATE TABLE `AIRPORT` (
  `ID` int(11) NOT NULL,
  `IDENT` varchar(100) NOT NULL,
  `TYPE` varchar(100) DEFAULT NULL,
  `NAME` varchar(200) DEFAULT NULL,
  `LATITUDEDEG` varchar(200) DEFAULT NULL,
  `LONGITUDEDEG` varchar(200) DEFAULT NULL,
  `ELEVATIONFT` varchar(200) DEFAULT NULL,
  `CONTINENT` varchar(45) DEFAULT NULL,
  `ISOCOUNTRY` varchar(45) DEFAULT NULL,
  `ISOREGION` varchar(45) DEFAULT NULL,
  `MUNICIPALITY` varchar(100) DEFAULT NULL,
  `SCHEDULEDSERVICE` varchar(100) DEFAULT NULL,
  `GPSCODE` varchar(100) DEFAULT NULL,
  `IATACODE` varchar(100) DEFAULT NULL,
  `LOCALCODE` varchar(100) DEFAULT NULL,
  `HOMELINK` varchar(200) DEFAULT NULL,
  `WIKIPEDIALINK` varchar(300) DEFAULT NULL,
  `KEYWORDS` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`IDENT`,`ID`),
  UNIQUE KEY `IDENT_UNIQUE` (`IDENT`),
  KEY `isocountry_idx` (`ISOCOUNTRY`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `COUNTRY` (
  `ID` int(11) NOT NULL,
  `CODE` varchar(45) DEFAULT NULL,
  `NAME` varchar(200) DEFAULT NULL,
  `CONTINENT` varchar(200) DEFAULT NULL,
  `WIKIPEDIALINK` varchar(500) DEFAULT NULL,
  `KEYWORDS` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CODE_UNIQUE` (`CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `runway` (
  `ID` int(11) NOT NULL,
  `AIRPORTREF` varchar(45) DEFAULT NULL,
  `AIRPORTIDENT` varchar(45) DEFAULT NULL,
  `LENGTHFT` varchar(45) DEFAULT NULL,
  `WIDTHFT` varchar(45) DEFAULT NULL,
  `SURFACE` varchar(45) DEFAULT NULL,
  `LIGHTED` varchar(45) DEFAULT NULL,
  `CLOSED` varchar(45) DEFAULT NULL,
  `LEIDENT` varchar(45) DEFAULT NULL,
  `LELATITUDEDEG` varchar(45) DEFAULT NULL,
  `LELONGITUDEDEG` varchar(45) DEFAULT NULL,
  `LEELEVATIONFT` varchar(45) DEFAULT NULL,
  `LEHEADINGDEGT` varchar(45) DEFAULT NULL,
  `LEDISPLACEDTHRESHOLDFT` varchar(45) DEFAULT NULL,
  `HEIDENT` varchar(45) DEFAULT NULL,
  `HELATITUDEDEG` varchar(45) DEFAULT NULL,
  `HELONGITUDEDEG` varchar(45) DEFAULT NULL,
  `HEELEVATIONFT` varchar(45) DEFAULT NULL,
  `HEHEADINGDEGT` varchar(45) DEFAULT NULL,
  `HEDISPLACEDTHRESHOLDFT` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `surface_idx` (`SURFACE`),
  KEY `airportident_idx` (`AIRPORTIDENT`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;